name: Swap AppService Slot

on: 
  workflow_dispatch:
permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
#
# Set up the following secrets in your repository:
#   AZURE_CREDENTIALS, REGISTRY_USERNAME, REGISTRY_PASSWORD, REGISTRY_URL
# 2. Change these variables for your configuration:
env:
  CONTAINER_REGISTRY: ${{ secrets.REGISTRY_URL }}.azurecr.io  # set secret with Container Registry URL, example : xyz.azurecr.io
  CONTAINER_IMAGE_NAME: msbuild-thailand-2025-wordcloud  # set this to your container image name, example: nodejsapp
  AZURE_RESOURCE_GROUP: rg-msbuildth2025-wordcloud

# AZURE_RESOURCE_GROUP: ActionsDemo   # set this to your Azure Resource group's name - Needed only if you are provisioning the app in the workflow
# AZURE_APP_PLAN: ActionPlan  # set this to your App service plan's name - Needed only if you are provisioning the app in the workflow
  
jobs:
  swap-app-service-slot:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    environment: DEV
    steps:
    - uses: actions/checkout@v4
    - name: Azure CLI Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
    - name: Swap App Service Slot
      run: |
         az webapp deployment slot swap --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AZURE_WEBAPP_NAME }} --slot stg